### ISSUE TITLE
Generation fails with go 1.22

### ISSUE THREAD

**Issue by tessig** [i-love-flamingo/graphql#99]
When generating graphql with go 1.22 the command panics 
`panic: runtime error: invalid memory address or nil pointer dereference`.

This is easily reproducible with an "empty" flamingo project.
```go
func main() {
	flamingo.App(
		[]dingo.Module{
			new(graphql.Module),
		},
	)
}
```

and `go run main.go graphql`

**Comment by carstendietrich** [comment]
fixed with #96
